# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Dotfiles folder
export DOTFILES=./

# Ack like nano
bindkey -v

ZSH_THEME="agnoster"

export UPDATE_ZSH_DAYS=7

# Plugin
plugins=(zsh-autosuggestions tmuxinator tmux vi-mode autojump)

# User configuration
export PATH="$HOME/.rvm/bin:$PATH"
export EDITOR="nano"

source $ZSH/oh-my-zsh.sh

export TERM="xterm-256color"
export EDITOR="nano"

# Alias
source $HOME/Documents/dotfiles/zsh/alias.zsh

bindkey '^ ' autosuggest-execute
RPROMPT="\$(~/.rvm/bin/rvm-prompt s i v g)%{$fg[yellow]%}[%*]"
# eval "$(pyenv init -)"
eval $(thefuck --alias)
source /etc/bash_completion.d/climate_completion